### ISSUE TITLE
Line 70

### ISSUE THREAD

**Issue by hoochiemama** [cybercdh/phishfinder#1]
Hi,

Generating this error consistently. New to this, so this could very well be my fault :)

python3 phishfinder.py --input urls.txt --output /phishing/kit/folder

  File "phishfinder.py", line 70
    print "[+]  Guessing: {}".format(guess_url)

**Comment by cybercdh** [comment]
Hey - is there anything more in your error message?

**Comment by hoochiemama** [comment]
Sorry, looks like the message was cut off when sending the first message, here it is in full:


![phish-error](https://user-images.githubusercontent.com/45691027/58254334-85539a00-7d38-11e9-801c-8a57ae02877a.png)

**Comment by cybercdh** [comment]
Hmm, does it work using python and not python3?

**Comment by hoochiemama** [comment]
Just with "python"

![phish-error1](https://user-images.githubusercontent.com/45691027/58265861-81327700-7d4e-11e9-94ab-ef46ce174dc2.png)

**Comment by cybercdh** [comment]
You’ll probably have to pip install - r requirements.txt again before running with python 2.7

**Comment by hoochiemama** [comment]
Will do, thx

**Comment by thirdeyeintelligence** [comment]
was this ever fixed i am getting same error

**Comment by hoochiemama** [comment]
Yes, converted the code to Python3 with 2to3. This resolved the issue. Runs perfectly now.

**Comment by cybercdh** [comment]
I've just updated the code to python3, apols for the delay. Hoping this now to be resolved?
