### ISSUE TITLE
Not downloading 

### ISSUE THREAD

**Issue by hoochiemama** [cybercdh/phishfinder#3]
Hi, just started seeing this behavior after gut pull  - 2days ago. Nothing is being downloaded. URL are bring checked, but that's it. Confirmed behavior against another instance running version from Oct. 2019.

**Comment by cybercdh** [comment]
K thanks, checking it out.

**Comment by cybercdh** [comment]
Should now be sorted, there was an issue with the encoding the of the URL once it was parsed. I've removed this and appears to be working. Note, there are few features this code doesnt implement which is bugging me and therefore I'm re-writing in Go; so watch this space for a much faster and feature-rich version soon!

**Comment by hoochiemama** [comment]
Thank you!!! Working perfectly. I use this tool weekly.
